name: PR Checklist
description: Adds comments to the PR.

inputs:
  pr-checklist-title:
    description: The title of the checklist
    required: true
  pr-checklist-body:
    description: The body of the checklist
    required: true

runs:
  using: composite
  steps:
    - name: Find PR Checklist 🔍
      uses: peter-evans/find-comment@v2
      id: find_comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ inputs.pr-checklist-title }}
    - name: Add PR Checklist
      if: ${{ success() && steps.find_comment.outputs.comment-id == '' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: |
          ${{ inputs.pr-checklist-title }}

          ${{ inputs.pr-checklist-body }}